const subjectCodes = [
  "AA",
"ABM",
"AC",
"ACC",
"ACE",
"AH",
"ALS",
"AM",
"AMN",
"AN",
"AR",
"ARD",
"ARX",
"AS",
"ASP",
"AUD",
"AX",
"AY",
"BA",
"BAA",
"BBB",
"BBC",
"BBD",
"BBP",
"BCP",
"BDC",
"BE",
"BFA",
"BFS",
"BH",
"BHD",
"BHT",
"BI",
"BIS",
"BL",
"BLD",
"BMA",
"BMC",
"BMD",
"BME",
"BMF",
"BMG",
"BMH",
"BMI",
"BMK",
"BMM",
"BMO",
"BMP",
"BMR",
"BMS",
"BMT",
"BMU",
"BN",
"BPM",
"BPS",
"BR",
"BRP",
"BS",
"BSE",
"BSM",
"BSN",
"BSP",
"BSS",
"BST",
"BT",
"BU",
"BV",
"BWS",
"BX",
"BXT",
"BY",
"BZ",
"BZD",
"CAH",
"CAS",
"CD",
"CDE",
"CDM",
"CDN",
"CE",
"CEG",
"CESEMI",
"CF",
"CFG",
"CG",
"CH",
"CHC",
"CK",
"CL",
"CLA",
"CLC",
"CM",
"CME",
"CMX",
"CN",
"CO",
"COS",
"COT",
"CP",
"CPE",
"CS",
"CSA",
"CSD",
"CSP",
"CSX",
"CT",
"CZ",
"DA",
"DAO",
"DBA",
"DE",
"DEP",
"DI",
"DL",
"DMA",
"DMB",
"DMC",
"DMD",
"DMP",
"DMR",
"DMS",
"DMX",
"DMY",
"DOS",
"DP",
"DS",
"DSA",
"DSC",
"DSE",
"DSN",
"DSS",
"DTK",
"DTS",
"DX",
"DY",
"EA",
"EB",
"EBA",
"EC",
"ECA",
"EE",
"EG",
"EHB",
"EL",
"ELC",
"ELR",
"EM",
"EMC",
"EN",
"ENC",
"ENV",
"EP",
"ES",
"ESE",
"ESP",
"ET",
"ETP",
"EU",
"EV",
"EX",
"FA",
"FAS",
"FD",
"FDP",
"FE",
"FIN",
"FMA",
"FMC",
"FMD",
"FME",
"FMS",
"FNA",
"FSA",
"FSC",
"FSD",
"FSE",
"FSP",
"FST",
"FT",
"GDM",
"GE",
"GEA",
"GEC",
"GEH",
"GEI",
"GEK",
"GEM",
"GEN",
"GENE",
"GEQ",
"GER",
"GES",
"GESS",
"GET",
"GEX",
"GL",
"GMS",
"GN",
"GPM",
"GS",
"GSC",
"GSE",
"GSG",
"GSN",
"GSS",
"GST",
"GXK",
"GXM",
"HI",
"HLE",
"HM",
"HR",
"HS",
"HSA",
"HSH",
"HSI",
"HSS",
"HY",
"IAN",
"ICH",
"ICL",
"ID",
"IDX",
"IE",
"IEC",
"IEL",
"IEM",
"IEN",
"IEU",
"IF",
"IFS",
"IGE",
"IGL",
"IHY",
"IJS",
"IL",
"IM",
"IMS",
"IND",
"INM",
"INT",
"IPH",
"IPL",
"IPM",
"IPS",
"IS",
"ISC",
"ISD",
"ISE",
"ISN",
"ISS",
"ISW",
"ISY",
"IT",
"ITS",
"IY",
"IZ",
"JS",
"KE",
"LA",
"LAB",
"LAC",
"LAD",
"LAF",
"LAG",
"LAH",
"LAI",
"LAJ",
"LAK",
"LAL",
"LAM",
"LAR",
"LAS",
"LAT",
"LAV",
"LAX",
"LC",
"LCC",
"LCD",
"LCJ",
"LE",
"LI",
"LL",
"LLA",
"LLB",
"LLD",
"LLJ",
"LN",
"LSE",
"LSM",
"LSX",
"LX",
"LZ",
"MA",
"MAE",
"MB",
"MBA",
"MBI",
"MC",
"MCH",
"MCI",
"MD",
"MDG",
"MDN",
"ME",
"MEM",
"MHR",
"MIC",
"MIT",
"MKT",
"ML",
"MLE",
"MMT",
"MNO",
"MO",
"MPA",
"MQ",
"MS",
"MST",
"MT",
"MTM",
"MUA",
"MUH",
"MUL",
"MUT",
"MUX",
"MW",
"NCC",
"NE",
"NEP",
"NEX",
"NFB",
"NFC",
"NG",
"NGN",
"NGT",
"NHS",
"NHT",
"NK",
"NM",
"NMC",
"NPS",
"NSS",
"NST",
"NSW",
"NTW",
"NUR",
"NX",
"OL",
"OMS",
"OT",
"OY",
"PA",
"PC",
"PE",
"PF",
"PFX",
"PH",
"PHM",
"PHS",
"PL",
"PLB",
"PLC",
"PLS",
"PM",
"POY",
"PP",
"PPH",
"PPHAPI",
"PPHBGP",
"PPHDHPP2",
"PPHDPI",
"PPHFLD",
"PPHHUT",
"PPHIGA",
"PPHITF",
"PPHMI",
"PPHMLD",
"PPHPED",
"PPHSUP",
"PPHU",
"PPX",
"PR",
"PRV",
"PS",
"PX",
"PY",
"QF",
"QT",
"RD",
"RE",
"REX",
"RS",
"RVC",
"RVN",
"RVSS",
"RVX",
"RX",
"RY",
"SA",
"SC",
"SCC",
"SCI",
"SDM",
"SE",
"SEA",
"SF",
"SG",
"SH",
"SKL",
"SLP",
"SM",
"SMA",
"SN",
"SP",
"SPH",
"SS",
"SSA",
"SSB",
"SSC",
"SSD",
"SSE",
"SSM",
"SSS",
"SSU",
"SSX",
"SSY",
"ST",
"STR",
"SW",
"SWD",
"SWE",
"SWK",
"SWM",
"SX",
"SXC",
"SXL",
"SXM",
"SXP",
"SYE",
"TBA",
"TC",
"TCE",
"TCN",
"TD",
"TDBN",
"TDCN",
"TDEE",
"TDEG",
"TDSC",
"TE",
"TEE",
"TG",
"TIC",
"TIE",
"TM",
"TMA",
"TME",
"TP",
"TR",
"TRA",
"TS",
"TSC",
"TTG",
"TX",
"UAC",
"UAI",
"UAR",
"UAS",
"UBM",
"UBZ",
"UCQ",
"UCS",
"UCV",
"UD",
"UEG",
"UFA",
"UFB",
"UFC",
"UFE",
"UFQ",
"UHB",
"UIS",
"UIT",
"ULS",
"ULT",
"UMS",
"UNL",
"UPC",
"UPI",
"UQF",
"UQR",
"URM",
"USC",
"USE",
"USHY",
"USLA",
"USP",
"USR",
"USS",
"USWP",
"UTC",
"UTOA",
"UTOB",
"UTOC",
"UTOD",
"UTOE",
"UTOM",
"UTON",
"UTOS",
"UTS",
"UTW",
"UWC",
"VM",
"WP",
"WR",
"XD",
"XFA",
"XFB",
"XFC",
"XFE",
"XFS",
"YCC",
"YCI",
"YCT",
"YHU",
"YID",
"YIL",
"YIR",
"YLC",
"YLE",
"YLF",
"YLG",
"YLL",
"YLN",
"YLS",
"YSC",
"YSH",
"YSP",
"YSS",
"ZB",
]

const subjectNames = [
  "Asian Studies",
  "Applied Biomedicine",
  "Architectural Conservation",
  "Accounting",
  "Arts and Cultural Entrepreneur",
  "Art History",
  "Application of Learning Sci",
  "Civil Engineering",
  "Singapore-MIT Alliance",
  "Anthropology",
  "Architecture",
  "Architecture By Design",
  "Architecture",
  "American Studies",
  "H3 Humanities & Soc Sc Res Prg",
  "Audiology",
  "FASS Special SEP Modules",
  "Anatomy",
  "SEP Exchange Module",
  "Accounting",
  "GD Advanced Placement Credits",
  "GD Transfer Credit Modules",
  "GD Transfer Credit Modules",
  "Business Policy",
  "Consulting Practicum (BIZ)",
  "Decision Sciences",
  "Engl For Acad Purposes (BRE)",
  "Finance",
  "Career Planning and Management",
  "Business",
  "Business (Honours Dissertation",
  "Business (Honours Thesis)",
  "Business Internship",
  "Independent Study Module in Bu",
  "Biological Sciences",
  "Business Leadership Developmen",
  "Master in Business Admin",
  "APEX-MBA (Chinese)",
  "Digital Fintech (BIZ)",
  "APEX-MBA (English)",
  "Finance",
  "Sustainable and Green Finance",
  "Human Capital Mgt & Analytics",
  "Biomedical Informatics",
  "Marketing",
  "Master in Public Administratio",
  "Management and Organisation",
  "Strategy and Policy",
  "Investmt & Portfolio Risk Mgmt",
  "Management",
  "Accounting",
  "UCLA-NUS Executive MBA",
  "Bioengineering",
  "Academic Orientation Modules",
  "Building Performance & Sust",
  "Building and Real Estate",
  "Graduate Research Seminar",
  "Building",
  "Business Economics",
  "Business Study Mission",
  "Innovation and Entrepreneurshp",
  "Business Policy",
  "Business Special Seminars",
  "Business Policy (Sp Topics)",
  "Business Analytics",
  "Building",
  "Behavioural Sci (Dentistry)",
  "Business Work-Study Internship",
  "Environmental Management",
  "Business Exchange Topic",
  "Biochemistry",
  "Business Policy",
  "Business Doctorate",
  "Child and Adolescent Health",
  "Comparative Asian Studies",
  "Chemistry with Management",
  "CDE Common Curriculum",
  "Cancer Science Institute S'por",
  "Cancer Science Institute S'por",
  "Civil Engineering",
  "Computer Engineering",
  "Civil Engineering Seminar",
  "Computational Finance",
  "Centre for Future-Ready Gradua",
  "Computing & Engineering Prog",
  "Chinese Studies",
  "Chinese Culture and Language",
  "China Studies",
  "Chinese Language",
  "Building",
  "Community Leadership Curriculu",
  "Chemistry",
  "Singapore-MIT Alliance",
  "Chemistry",
  "Chemical Engineering",
  "Public Health",
  "Computational Thinking for Sci",
  "Computational Thinking",
  "Computing",
  "Singapore - MIT Alliance",
  "Computer Sci/Information Sys",
  "Cultural Studies",
  "Computing with Scientific Data",
  "Independent Study Module (SoC)",
  "SOC Exchange Breadth Module",
  "Civil Engineering",
  "Computational Science",
  "Dental Anatomy & Histology",
  "Analytics and Operations",
  "Business Analytics",
  "Environmental Management",
  "Master of Urban Planning",
  "Dentistry",
  "Digital Leadership",
  "Design Your Own Module (FASS)",
  "Design Your Own Module (BIZ)",
  "Design Your Own Module (SoC)",
  "Design Your Own Module (SDE)",
  "Design Your Own Module (USP)",
  "Design Your Own Module (RVRC)",
  "Design Your Own Module (FoS)",
  "Design Your Own Module (PVO)",
  "Design Your Own Module (PVO)",
  "Operations and SCM",
  "Data Protection",
  "Decision Sciences",
  "Data Science and Analytics",
  "Decision Sciences",
  "Data Science and Economics",
  "Business Analytics",
  "Operations and SCM",
  "Design Thinking",
  "Temasek Defence Systems Inst",
  "SDE Exchange Module",
  "Dentistry",
  "Engl For Acad Purposes (FASS)",
  "Enterprise Business Analytics",
  "Enterprise Business Analytics",
  "Economics",
  "Applied Economics",
  "Electrical Engineering",
  "Engineering",
  "Ethics of Health Rsrch & Biote",
  "English Language",
  "EL Coursework MA",
  "English Language (RLC)",
  "English (Music)",
  "Business",
  "English Literature",
  "EN Coursework MA",
  "Environmental Studies",
  "Epidemiology",
  "English",
  "Environmental Science & Engrg",
  "Engineering Science Programme",
  "Engl For Acad Purposes (SoC)",
  "Entrepreneurship",
  "European Studies",
  "Environmental Engineering",
  "FOE Exchange UEM",
  "Finance & Accounting",
  "Arts and Social Sciences",
  "First Aid",
  "French Double Degree Programme",
  "Financial Engineering",
  "Finance",
  "Freshman Seminar Modules",
  "Freshmen Seminar (SOC)",
  "Freshmen Seminar (SDE)",
  "Freshmen Seminar(FOE)",
  "Freshman Seminar (FoS)",
  "Financial Accounting",
  "Freshmen Seminar (FASS)",
  "Forensic Science",
  "Freshmen Seminar (SDE)",
  "Freshmen Seminar (FoE)",
  "Field Service Project",
  "Food Science and Technology",
  "FinTech (Financial Technology)",
  "GEM/SSX Dummy Module",
  "Geography",
  "Data Literacy",
  "Gen Edn (Cultures & Cnts)",
  "General Edn (Human Cultures)",
  "Digital Literacy",
  "General Education (Gen Knwldg)",
  "General Education (Modes Inq)",
  "Communities and Engagement",
  "Human Genetics",
  "General Education (Asking Que)",
  "General Education (Qua Reason)",
  "General Edn(Singapore Studies)",
  "Gen Edn (SG Studies)-New",
  "Gen Edn(Thinking & Epxression)",
  "Gen Edn (Critq & Exp)",
  "Global Studies",
  "Duke-Nus Graduate Medical Sch",
  "Gender Studies",
  "General Practice Management",
  "Nus Grad Sch For Int Sci & Eng",
  "NUS Graduate School for Integr",
  "Exchange Modules",
  "Graphene series of NGS modules",
  "Neuro-series of NGS modules",
  "Seminar series of NGS modules",
  "Translational series of NGS mo",
  "General Education (Gen Knw Tf)",
  "General Education (Mod Inq Tf)",
  "Healthcare Improvement",
  "Healthcare Law & Ethics",
  "Health Management",
  "Human Resource Management",
  "CHS Modules",
  "CHS Common (Asian Studies)",
  "CHS Common (Humanities)",
  "CHS Common (Sci Inquiry)",
  "CHS Common (Social Sciences)",
  "History",
  "Anthropology(Ext'd Internship)",
  "Chinese Studies (Ext Intnshp)",
  "Chinese Language (Ext Intnshp)",
  "Industrial Design",
  "Industrial Design",
  "Industrial & Systems Engrg",
  "Economics (Ext Intnshp)",
  "English Language (Ext Intnshp)",
  "Ideas and Exposition Module",
  "English Lit (Ext Intnshp)",
  "European Studies (Ext Intnshp)",
  "Information & Comms Mgmt",
  "Information Security",
  "Geography (Ext Intnshp)",
  "Extended Internship",
  "History (Ext Intnshp)",
  "Japanese Studies (Ext Intnshp)",
  "IT Leadership",
  "Credit Transfer (IMCB Modules)",
  "Malay Studies (Ext Intnshp)",
  "Industry 4.0",
  "Comm & New Media (Ext Intnshp)",
  "Interpreting",
  "Philosophy (Ext Intnshp)",
  "Psychology (Ext Intnshp)",
  "Infrastructure and Project Mgm",
  "Political Sc (Ext Intnshp)",
  "Information Systems",
  "Sociology (Ext Intnshp)",
  "Integrated Sustainable Design",
  "SEAsian Studies (Ext Intnshp)",
  "Extended SouthAsian Intership",
  "Systems Analysis",
  "Social Work (Ext Intnshp)",
  "Intelligent Systems",
  "Information Technology",
  "Theatre Studies (Ext Intnshp)",
  "Independent Study Module",
  "International Studies",
  "Japanese Studies",
  "Knowledge Engineering",
  "Landscape Architecture",
  "Language (Bahasa Indonesia)",
  "Language (Chinese)",
  "Landscape Architecture",
  "Language (French)",
  "Language (German)",
  "Language (Hindi)",
  "Language (Italian)",
  "Language (Japanese)",
  "Language (Korean)",
  "Language (Tamil)",
  "Language (Malay)",
  "Language (Arabic)",
  "Language (Spanish)",
  "Language (Thai)",
  "Language (Vietnamese)",
  "Language (Exchange)",
  "Law (Compulsory)",
  "Law Compulsory (Certificate)",
  "Law (Grad Dip Compulsory)",
  "Law (JD Compulsory)",
  "Law (Exchange Modules)",
  "The Logistics Inst - Asia Pac",
  "Law (Electives)",
  "Law (Compulsory)",
  "Law (Compulsory)",
  "Law (Grad Dip Electives)",
  "Law (JD Electives)",
  "Electives - NYU-NUS LLB/LLM",
  "Environmental Life Sciences En",
  "Life Sciences",
  "Life Sciences",
  "Environmental Law",
  "Law",
  "Mathematics",
  "Intl Finance and Investment",
  "Mechano-Biology",
  "Master in Business Admin",
  "Mechanobiology Institute Singa",
  "Microbiology",
  "Mechanical Engineering",
  "Clinical Investigation",
  "Medicine",
  "Medicine",
  "Nursing",
  "Mechanical & Production Engrg",
  "Master of Science in Env Mgmt",
  "Managing Human Resources",
  "Microbiology",
  "Massachusetts Inst of Tech",
  "Marketing",
  "Materials Science",
  "Materials Science",
  "Technopreneurship",
  "Management and Organisation",
  "Management and Organisation",
  "Maritime Management & Law",
  "Mathematics (FASS)",
  "Malay Studies",
  "Materials Science and Engrg",
  "Management of Information Tech",
  "Maritime Technology and Manage",
  "Music (Applied Studies)",
  "Music (Contextual Studies)",
  "Music (Languages)",
  "Music (Theory)",
  "Music Studies (Exchange)",
  "Science Communication",
  "NUS Career Centre",
  "Nanoengineering Programme",
  "Impact Experience Project",
  "Making Connections GEX",
  "NUSC Overseas Exchge Mod (HSS)",
  "NUSC Overseas Exchge Mod (ST)",
  "NUS Graduate School",
  "Global Narratives",
  "Global Social Thoughts",
  "Making Connections HSS",
  "NUSC Making Connections-HSS/ST",
  "Engl For Acad Purposes (BIZ)",
  "Communications and New Media",
  "Communication",
  "NUSC Computational Prob Solvin",
  "Science and Society",
  "Making Connections ST",
  "Understanding the Social World",
  "Thinking with Writing",
  "Nursing",
  "ALCNS Exchange Module",
  "Oral Biology",
  "Oral & Maxillofacial Surgery",
  "Offshore Technology",
  "Oral Pathology",
  "Pharmacology",
  "Physics",
  "Philosophy, Politics and Econ",
  "Project & Facilities Mgmt",
  "Project & Facilities Mgmt",
  "Philosophy",
  "Precision Health and Medicine",
  "Pharmaceutical Sciences",
  "Psychology",
  "Psychology",
  "Clinical Psychology",
  "PL (Soft Skills)",
  "Building and Real Estate",
  "Breadth/UEM from APC (Poly)",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "Lee Kuan Yew Sch of Public Pol",
  "LKYSPP Department Exchange Mod",
  "Pharmacy",
  "Preventive Dentistry",
  "Political Science",
  "Pathology",
  "Physiology",
  "Quantitative Finance",
  "Quantum Information",
  "Restorative Dentistry",
  "Real Estate",
  "Real Estate SEP Module",
  "Dentistry (UROP)",
  "RVRC â€“ Cultures and Connection",
  "RVRC-Communities and Engagment",
  "RVRC â€“ Singapore Studies",
  "RVRC â€“ Critique and Expression",
  "Religious Studies",
  "Dentistry",
  "Systems Analysis",
  "Sociology",
  "Scientific Computation",
  "Science",
  "Systems Architecture",
  "Southeast Asian Studies",
  "Contemporary Southeast Asia",
  "Science Foundation",
  "Software Engineering",
  "Chemical & Biomolecular Engrg",
  "FoS Exchange Enrichment Module",
  "Speech & Language Pathology",
  "Singapore-MIT Alliance",
  "Singapore-MIT Alliance",
  "South Asian Studies",
  "Special Science Modules",
  "School of Public Health",
  "Singapore Studies",
  "Singapore Studies (FASS)",
  "Singapore Studies (BIZ)",
  "Science Communication",
  "Singapore Studies (SDE)",
  "Singapore Studies (FoE)",
  "Singapore Studies (SoM)",
  "Singapore Studies (FoS)",
  "Singapore Studies (UT RCs)",
  "Singapore Studies Exchange Mod",
  "Singapore Studies (YSTCM)",
  "Statistics",
  "Career Preparation",
  "Social Work",
  "Social Work",
  "Software Engineering",
  "Correctional Rehabilitation",
  "Social Work",
  "FoS Exchange Enrichment Module",
  "FoS Exchange Enrichment Module",
  "FoS Exchange Enrichment Module",
  "FoS Exchange Enrichment Module",
  "FoS Exchange Enrichment Module",
  "Industrial & System Engg",
  "Business Analytics",
  "Bachelor of Technology Prog",
  "Civil Engineering",
  "Chemical Engineering",
  "Design Technology",
  "Bioengineering",
  "Chemical & Biomolecular Engrg",
  "Electrical & Computer Engrg",
  "Talent Dvlpmt Prog (FoE)",
  "Talent Dvlpmt Prog (FoS)",
  "Bachelor of Technology Prog",
  "Electronics Engineering",
  "Bachelor of Technology (Eng)",
  "Information and Communications",
  "Industrial and Management Eng",
  "Bachelor of Technology Prog",
  "Mathematics",
  "Mechanical Engineering",
  "Civil Engineering",
  "Technopreneurship",
  "Translation",
  "Theatre Studies",
  "Supply Chain Management",
  "Bachelor of Technology (Eng)",
  "Bachelor of Technology Prog",
  "USP Overseas Exchange Module",
  "USP Overseas Exchange Module",
  "USP 1st Tier Modules",
  "USP Course Based Module (FASS)",
  "USP 1st Tier Modules",
  "USP Course Based Module (BIZ)",
  "USP-Yuanpei China Studies",
  "USP Course Based Module (SoC)",
  "USP 1st Tier Modules",
  "Architecture",
  "USP Course Based Module (FoE)",
  "USP Overseas Exchange Module",
  "USP Overseas Exchange Module",
  "USP Overseas Exchange Module",
  "Overseas Exchange Module (Enri",
  "Overseas Exchange Module",
  "USP 1st Tier Modules",
  "USP Independent Study Module",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP Research Module",
  "USP Course Based Module (FoS)",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "USP Senior Seminar",
  "USP 1st Tier Modules",
  "USP 1st Tier Modules",
  "UTown Colleges",
  "UG Teaching Opp Program (FASS)",
  "UG Teaching Opp Program (BIZ)",
  "UG Teaching Opp Program (SoC)",
  "UG Teaching Opp Program (SDE)",
  "UG Teaching Opp Program (FoE)",
  "UG Teaching Opp Program(YSTCM)",
  "UG Teaching Opp Program(ALCNS)",
  "UG Teaching Opp Program (FoS)",
  "UTown â€“ Singapore Studies",
  "UTown â€“ Writing Programme",
  "USP 1st Tier Modules",
  "Palliative Medicine",
  "Writing Programme",
  "Workplace Readiness",
  "Cross Disciplinary Modules",
  "Integrated Honours Project",
  "Integrated Honours Project",
  "Integrated Honours Project",
  "Integrated Honours Project",
  "Integrated Honours Project-FoS",
  "Yale-NUS College's Common Curr",
  "Yale-NUS College's CIPE Progra",
  "Yale-NUS Collegeâ€™s Transition",
  "Yale-NUS Collegeâ€™s Humanities",
  "Yale-NUS Collegeâ€™s Interdiscip",
  "Yale-NUS College Independent L",
  "Yale-NUS Indepen Reading & Rsh",
  "Yale-NUS College's Lang Chines",
  "Yale-NUS Dum Mod Credit Trsf",
  "Yale-NUS College's Lang French",
  "Yale-NUS College's Lang Greek",
  "Yale-NUS College's Lang Latin",
  "Yale-NUS College's Lang Sanskr",
  "Yale-NUS College's Languages",
  "Yale-NUS Collegeâ€™s Sciences",
  "Yale-NUS College's Short Cours",
  "Yale-NUS College's Special Prg",
  "Yale-NUS Collegeâ€™s Social Sci",
  "Computational Biology",    
]

const moduleSubjects = subjectCodes.map((code, i) => ({name: moduleSubjects[i], subject: code}))

const DEFAULT_DATA = {
    moduleSubjects: moduleSubjects,
      correctModules: [
        {
          subject: "CS",
          code: "4249",
          courseName: "Phenomena and Theories of Human-Computer Interaction",
        },
        {
          subject: "ACC",
          code: "1701X",
          courseName: "Accounting for Decision Makers",
        },
        {
          subject: "GET",
          code: "1050",
          courseName: "Computational Reasoning",
        },
      ],
      allModules: [
        {
          subject: "CS",
          code: "4249",
          courseName: "Phenomena and Theories of Human-Computer Interaction",
        },
        {
          subject: "ACC",
          code: "1701X",
          courseName: "Accounting for Decision Makers",
        },
        {
          subject: "GET",
          code: "1050",
          courseName: "Computational Reasoning",
        },
    ]
};

const data = (state = DEFAULT_DATA, action) => {
    switch (action.type) {
      default:
        return state
    }
  }
  
  export default data;